cuz 10.14 just has to be different (bz2)

diff --git a/.github/workflows/prebuilt.yml b/.github/workflows/prebuilt.yml
--- a/.github/workflows/prebuilt.yml
+++ b/.github/workflows/prebuilt.yml
@@ -42,7 +42,11 @@ jobs:
         uses: actions/checkout@v6
       - name: download SDK
         run: |
-          wget -P tarballs https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.version }}/MacOSX${{ inputs.version }}.sdk.tar.xz
+          # Try tar.xz first, fall back to tar.bz2 if not found
+          if ! wget -P tarballs https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.version }}/MacOSX${{ inputs.version }}.sdk.tar.xz; then
+            echo "tar.xz not found, trying tar.bz2..."
+            wget -P tarballs https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.version }}/MacOSX${{ inputs.version }}.sdk.tar.bz2
+          fi
       - name: build osxcross
         run: |
           UNATTENDED=1 TARGET_DIR=${{ github.workspace }}/osxcross ./build.sh         
